service: js-guild-twilio

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  textResponder:
    handler: handler.textResponder
    # HttpApi are handled via AWS through API Gateway
    events:
      - httpApi:
          path: /textresponder
          method: post

